# Generated by Django 4.2.2 on 2023-07-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0002_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default=False, max_length=4),
        ),
    ]
