# Generated by Django 4.2.2 on 2023-07-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
