# Generated by Django 4.2.2 on 2023-08-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='status',
        ),
    ]
