# Generated by Django 4.2.2 on 2023-08-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slotbooking_user'),
        ('order', '0003_remove_orderdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='slot_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.slotbooking'),
        ),
    ]
