# Generated by Django 4.2.2 on 2023-08-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderdetails_slot_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
